### ISSUE TITLE
Bug (PIP gets killed on Refresh)

### ISSUE THREAD

**Issue by abhishek227** [mtsmfm/pip-any-site#11]
After the recent update pip window gets killed on refresh
checked on Chrome Version 127.0.6533.89 and Brave and other Chromium-based browsers 

Steps to reproduce 
1. Lauch PIP window
2. Refresh the same window and the pip window gets killed 
![aw6Tcq0obF](https://github.com/user-attachments/assets/5c3f7d0c-a748-44bd-91eb-a07f37a5b329)

**Comment by mtsmfm** [comment]
@abhishek227 Thank you for your report. Unfortunately, with manifest version 3, there's no way to create pip window in extension's own context.

I've reported this issue 6 month ago but it's still not fixed and surprisingly MV3 deprecation has been started.

Please see this ticket and vote if you are uncomfortable with this limitation.

https://issues.chromium.org/issues/326889650
