### ISSUE TITLE
Fail to install extension because of "Package is invalid"

### ISSUE THREAD

**Issue by pankona** [mtsmfm/pip-any-site#3]
I've tried to install this awesome extension via chrome web store but it failed.
Here's a screenshot of the error. 

![image](https://user-images.githubusercontent.com/6533008/82639280-63d70800-9c43-11ea-92ff-89ea407571ed.png)

**Comment by mtsmfm** [comment]
Thank you for reporting!

I hope it's fixed by this https://github.com/mtsmfm/pip-any-site/commit/0f6c655e2db6366991fe5fff34c810e5aa0e384b

**Comment by mtsmfm** [comment]
It's published and I confirmed it can be installed now!

**Comment by pankona** [comment]
@mtsmfm 

Thanks! I've confirmed it can work now! 💪
